#!/bin/sh
PACKAGE="python-amqp-tools"
GIT_REV=`git rev-parse --short HEAD | tr -d '\n'`
VPART="0.pre.$GIT_REV"
if [ "$BUILD_NUMBER" != "" ]; then
  VPART=$BUILD_NUMBER
fi

VERSION="0.0.$VPART"
echo $VERSION
TMP_DIR="/tmp/$PACKAGE-$VERSION-$ITERATION"

rm -rf $TMP_DIR
mkdir $TMP_DIR || exit 1
rsync -a *.py $TMP_DIR/ || exit 1
fpm -t deb -d 'python-amqplib' -m '<infra@timgroup.com>' -s dir --architecture all -C $TMP_DIR --name $PACKAGE --version $VERSION --prefix /usr/bin . || exit 1
rm -rf $TMP_DIR || exit 1

